SELECT PAGAMENTO.*,
       TIPO.ID AS tipoId, 
       TIPO.NOME AS tipoNome, 
       IMOVEL.ID AS imovelId, 
       IMOVEL.DESCRICAO AS imovelDescricao
 FROM PAGAMENTOS PAGAMENTO
 JOIN IMOVEIS IMOVEL ON PAGAMENTO.IMOVEL = IMOVEL.ID 
 JOIN TIPOIMOVEIS TIPO ON IMOVEL.TIPO = TIPO.ID
 ORDER BY PAGAMENTO.IMOVEL